// Code generated by goctl. DO NOT EDIT.
package types

type TransRequest struct {
	Amount   int64 `json:"amount"`
	UserId   int64 `json:"userId"`
	ToUserId int64 `json:"toUserId"`
}

type TransResponse struct {
	Id int64 `json:"id"`
}
